export const servicePointModalInputs = [
    [
        {
            id: 'service-point-name',
            inputClassName: 'bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 mb-4',
            name: 'service-point-name',
            label: 'Hizmet Noktasi Ismi',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'text',
            placeholder: '',
            pattern: '^[A-Za-z0-9]',
            extra: '',
            required: true,
            error: 'Hizmet Noktasi Ismi Bos Birakilamaz.',
            wrapperClassName: '',
        }, {
            id: 'service-point-reseller',
            inputClassName: 'bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 mb-4',
            name: 'service-point-reseller',
            label: 'Hizmet Noktasi Saticisi',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'dropdown',
            placeholder: '',
            pattern: '^[A-Za-z0-9]',
            extra: {
                items: ['Satici 1', 'Satici 2', 'Satici 3']
            },
            required: true,
            error: 'Hizmet Noktasi Reseller Bos Birakilamaz.',
            wrapperClassName: '',
        }, {
            id: 'service-point-company',
            inputClassName: 'bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 mb-4',
            name: 'service-point-company',
            label: 'Hizmet Noktasi Sirketi',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'dropdown',
            placeholder: '',
            pattern: '^[A-Za-z0-9]',
            extra: {
                items: ['Sirket 1', 'Sirket 2', 'Sirket 3']
            },
            required: true,
            error: 'Hizmet Noktasi Sirketi Bos Birakilamaz.',
            wrapperClassName: '',
        }, {
            inputClassName: '',
            id: 'modal-next-button-to-2',
            name: 'modal-next-button',
            label: 'Ileri',
            labelClassName: '',
            type: 'button',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'flex flex-col',
        }
    ],
    [
        {
            id: 'service-point-property',
            inputClassName: 'bg-gray-50 border text-gray-900 text-sm rounded-lg block w-full p-2.5 mb-4',
            name: 'service-point-property',
            label: 'Hizmet Noktasi Ozelligi',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'dropdown',
            placeholder: '',
            pattern: '',
            extra: {
                items: ['AVM', 'Sosyal Tesis']
            },
            required: false,
            error: 'Hizmet Noktasi Ozelligi Bos Birakilamaz.',
            wrapperClassName: '',
        }, {
            id: 'service-point-number1',
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            name: 'service-point-number1',
            label: 'Servis Noktasi Sorumlu Telefon',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'number',
            placeholder: '(555) 123 12 12',
            pattern: '[0-9]{10}',
            extra: '',
            required: true,
            error: 'Hizmet Noktasi Telefon Numarasi Bos Birakilamaz',
            wrapperClassName: '',
        }, {
            id: 'service-point-number2',
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            name: 'service-point-number2',
            label: 'Servis Noktasi Sorumlu Telefon',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'number',
            placeholder: '(555) 123 12 12',
            pattern: '[0-9]{10}',
            extra: '',
            required: false,
            error: 'Hizmet Noktasi Telefon Numarasi Bos Birakilamaz',
            wrapperClassName: 'flex flex-col',
        }, {
            id: 'service-point-address',
            inputClassName: 'mb-4',
            name: 'service-point-address',
            label: 'Hizmet Noktasi Adresi',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'textarea',
            placeholder: 'Adresi giriniz...',
            pattern: '',
            extra: '',
            required: true,
            error: 'Hizmet Noktasi Adresi Bos Birakilamaz',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: '',
            id: 'modal-next-button-to-2',
            name: 'modal-next-button',
            label: 'Ileri',
            labelClassName: '',
            type: 'button',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'flex flex-col',
        }
    ], [
        {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-x-coor',
            name: 'service-point-x-coor',
            label: 'Hizmet Noktasi X Koordinati',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'text',
            placeholder: '',
            pattern: '[0-9]',
            extra: '',
            required: true,
            error: 'Hizmet Noktasi X Koordinati Bos Birakilamaz.',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-y-coor',
            name: 'service-point-y-coor',
            label: 'Hizmet Noktasi Y Koordinati',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'text',
            placeholder: '',
            pattern: '[0-9]',
            extra: '',
            required: true,
            error: 'Hizmet Noktasi Y Koordinati Bos Birakilamaz.',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: '',
            id: 'modal-prev-button-to-1',
            name: 'modal-prev-button',
            label: 'Geri',
            labelClassName: '',
            type: 'button',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'inline-flex w-1/3 justify-start',
        }, {
            inputClassName: '',
            id: 'modal-next-button-to-3',
            name: 'modal-next-button',
            label: 'Ileri',
            labelClassName: '',
            type: 'button',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'inline-flex w-1/3 justify-end',
        }
    ], [
        {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-city',
            name: 'service-point-city',
            label: 'Hizmet Noktasi Il',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'dropdown',
            placeholder: '',
            pattern: '',
            extra: {
                items: [],
            },
            required: true,
            error: 'Hizmet Noktasi Sehri Bos Birakilamaz.',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-district',
            name: 'service-point-district',
            label: 'Hizmet Noktasi Ilce',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'dropdown',
            placeholder: '',
            pattern: '',
            extra: {
                items: [],
            },
            required: true,
            error: 'Hizmet Noktasi Ilce Bos Birakilamaz.',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-payment-methods',
            name: 'service-point-payment-methods',
            label: 'Servis Noktasi Odeme Yontemleri',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'dropdown',
            placeholder: '',
            pattern: '',
            extra: {
                items: ['Nakit', 'Kredi Karti', 'Banka Karti']
            },
            required: true,
            error: 'Hizmet Noktasi Odeme Yontemi Bos Birakilamaz',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-parking',
            name: 'service-point-parking',
            label: 'Servis Noktasi Ucretsiz Park',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'radio',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full my-2 p-2.5',
            id: 'service-point-opportunity',
            name: 'service-point-opportunity',
            label: 'Hizmet Noktasi Olanaklari',
            labelClassName: 'block mb-2 text-sm font-medium text-gray-900',
            type: 'checkbox',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: '',
            id: 'modal-prev-button-to-2',
            name: 'modal-prev-button',
            label: 'Geri',
            labelClassName: '',
            type: 'button',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'flex flex-col',
        }, {
            inputClassName: '',
            id: 'modal-submit-button',
            name: 'modal-submit-button',
            label: 'Kaydet',
            labelClassName: '',
            type: 'submit',
            placeholder: '',
            pattern: '',
            extra: '',
            required: false,
            error: '',
            wrapperClassName: 'flex flex-col',
        }
    ]
]