const tablePlaceholderInitialValue = {
    id: 1,
    trxId: 1,
    StationConnectorID: 1,
    StationConnectorConnectorNr: 1,
    StationChargePointCode: '1',
    MeterStartDate: '1',
    MeterFinishDate: '1',
    EnergyUsed: 1,
    StartDate: '1',
    FinishDate: '1',
    ChargeProcessElapsedTime: 1,
    UnitPrice: 1,
    PriceENRJ: 1,
    PriceSRV: 1,
    CommissionServicePointPrice: null,
    CommissionResellerPrice: null,
    TotalAmountWithOutKDV: 1,
    TotalAmount: 1,
    ChargingStatus: 1,
    ChargingStatusMessage: '1',
    StationID: 1,
    StationName: '1',
    ResellerCompanyID: 1,
    CompanyID: 1,
    StationChargePointConnectorTypeName: '1',
    ConsumerCompanyID: 1,
    BatteryPercentDesc: '1',
    BatteryBeginningPercent: 1,
    BatteryPercent: 1,
    EMail: '1',
    GSMNr: '1',
    socketNo: 1,
    kWh: 1,
    priceCalculationTime: 1,
    electricityAmount: 1,
    servicePrice: 1,
    bankOrderNo: '1',
    paidAmount: 1,
    preChargeAmount: 1,
    plate: 1,
    brand: '1',
    model: '1',
};

export {
    tablePlaceholderInitialValue,
};
