import { IBaseTableColumn } from '../BaseTable/BaseTableInterface';

export const NOTIFICATION_TABLE_COLUMNS: IBaseTableColumn[] = [
  {
    header: 'Bildirim Bilgi Tipi',
    accessor: 'notificationInfoTypeRID',
    field: 'notificationInfoTypeRID',
    id: 'notificationInfoTypeRID',
    isRemovable: false,
    type: 'string',
  },
  {
    header: 'Bildirim Tipi',
    accessor: 'notificationType',
    field: 'notificationType',
    id: 'notificationType',
    isRemovable: false,
    type: 'string',
  },
  {
    header: 'Kategori',
    accessor: 'notificationPushCategoryName',
    field: 'notificationPushCategoryName',
    id: 'notificationPushCategoryName',
    isRemovable: false,
    type: 'string',
  },
  {
    header: 'Başlık',
    accessor: 'title',
    field: 'title',
    id: 'title',
    isRemovable: false,
    type: 'string',
  },
  {
    header: 'İçerik',
    accessor: 'message',
    field: 'message',
    id: 'message',
    isRemovable: false,
    type: 'string',
  },
  {
    header: 'Başlangıç Tarihi',
    accessor: 'startedDate',
    field: 'startedDate',
    id: 'startedDate',
    isRemovable: false,
    type: 'date',
  },
  {
    header: 'İşlem Tarihi',
    accessor: 'processedDate',
    field: 'processedDate',
    id: 'processedDate',
    isRemovable: false,
    type: 'date',
  },
  {
    header: 'Oluşturulma Tarihi',
    accessor: 'createdDate',
    field: 'createdDate',
    id: 'createdDate',
    isRemovable: false,
    type: 'date',
  },
  {
    header: 'Teslim Durumu',
    accessor: 'isDelivery',
    field: 'isDelivery',
    id: 'isDelivery',
    isRemovable: false,
    type: 'boolean',
  },
  {
    accessor: 'actions',
    align: 'center',
    field: 'actions',
    header: 'Aksiyonlar',
    id: 'actions',
    isRemovable: false,
    type: 'custom',
  },
];
