export const ENDPOINTS = {
  AUTH: '/Auth',
  USERS: '/Users',
  LOGIN: '/Login',
  LANGUAGE_LIST: '/Language/LanguagesList',
  RESOURCE_TEXT: '/ResourceText',
  GET_BY_KEY_LIST: '/GetByKeyList',
  DASHBOARD: '/Dashboard',
  GET_DASHBOARD_ITEMS: '/GetDashboardItems',
  GET_DASHBOARD_ITEM_DATA: '/GetDashboardItemData',
  UPDATE_MULTIPLE: '/UpdateMultiple',
  SERVICE_POINT: '/ServicePoint',
  GET_ALL_POINTS: '/GetAllPoints',
  DELETE_STATION: '/DeleteStation',
};
