export const ENDPOINTS = {
  AUTH: '/Auth',
  DASHBOARD: '/Dashboard',
  DELETE_STATION: '/DeleteStation',
  GET_ALL_POINTS: '/GetAllPoints',
  GET_BRANDS: '/GetBrands',
  GET_BY_KEY_LIST: '/GetByKeyList',
  GET_CONNECTOR_MODELS: '/GetConnectorModels',
  GET_DASHBOARD_ITEM_DATA: '/GetDashboardItemData',
  GET_DASHBOARD_ITEMS: '/GetDashboardItems',
  GET_MODELS: '/GetModels',
  LANGUAGE_LIST: '/Language/LanguagesList',
  LOGIN: '/Login',
  RESOURCE_TEXT: '/ResourceText',
  SERVICE_POINT: '/ServicePoint',
  UPDATE_MULTIPLE: '/UpdateMultiple',
  USERS: '/Users',
  VALUES: '/Values',
};
