export const successResultServices = [
  'addServicePointImage',
  'addNotification',
  'cancelNotification',
  'createTariff',
  'deleteTariff',
  'editNotification',
  'removeServicePointImage',
  'addNewKnowledgeBase',
  'editKnowledgeBase',
  'removeKnowledgeBase',
  'addNewKnowledgeBaseCategory',
  'editKnowledgeBaseCategory',
  'removeKnowledgeBaseCategory',
];
