import { Montserrat} from 'next/font/google';
import ClientComponent from './ClientComponent';
import './global.css';

export const metadata = {
  title: 'Welcome to Sharz.net',
  description: 'Generated by Sharz.net developed by Ufuk Tas&Turgut Karadag',
};

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

const RootLayout = ({ children }: { children: React.ReactNode; }) => {
  return (
    <html className={`${montserrat.className}`} lang="en">
      <body>
        <ClientComponent>
          {children}
        </ClientComponent>
      </body>
    </html>
  );
};

export default RootLayout;
