import './global.css';
import StoreProvider from './StoreProvider';

export const metadata = {
  title: 'Welcome to Sharz.net',
  description: 'Generated by Sharz.net authored by Ufuk Tas',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoreProvider>
  );
}
