import { IBaseTableColumn } from '../BaseTable/BaseTableInterface';

export const FEEDBACKS_TABLE_COLUMNS: IBaseTableColumn[] = [
  {
    accessor: 'rid',
    field: 'rid',
    header: 'ID',
    id: 'rid',
    isRemovable: false,
    type: 'number',
  },
  {
    accessor: 'userID',
    field: 'userID',
    header: 'Kullanıcı ID',
    id: 'userID',
    isRemovable: false,
    type: 'number',
  },
  {
    accessor: 'userName',
    field: 'userName',
    header: 'Kullanıcı Adı',
    id: 'userName',
    isRemovable: false,
    type: 'string',
  },
  {
    accessor: 'email',
    field: 'email',
    header: 'Email',
    id: 'email',
    isRemovable: false,
    type: 'string',
  },
  {
    accessor: 'message',
    field: 'message',
    header: 'Mesaj',
    id: 'message',
    isRemovable: false,
    type: 'string',
  },
  {
    accessor: 'createDate',
    field: 'createDate',
    header: 'Oluşturulma Tarihi',
    id: 'createDate',
    isRemovable: false,
    type: 'date',
  },
  {
    accessor: 'contactMessageTypeValueAggregates',
    field: 'contactMessageTypeValueAggregates',
    header: 'Geri Bildirim Tipi',
    id: 'contactMessageTypeValueAggregates',
    isRemovable: false,
    type: 'custom',
  },
];
