export { default as CloseIcon } from './close/close';
export { default as FAQIcon } from './faq/faq';
export { default as GiftBoxIcon } from './giftBox/giftBox';
export { default as HamburgerMenuIcon } from './hamburgerMenu/hamburgerMenu'
export { default as InfoIcon } from './info/info';
export { default as LocationIcon } from './location/location';
export { default as PenIcon } from './pen/pen';
export { default as PersonIcon } from './person/person';
export { default as TrashIcon } from './trash/trash';